import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = 'https://xscdwdnjujpkczfhqrgu.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhzY2R3ZG5qdWpwa2N6Zmhxcmd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEzMzEwNjgsImV4cCI6MjA3NjkwNzA2OH0.xuVAkWA5y1oDW_jC52I8JJXF-ovU-5LIBsY9yXzy6cA';

export const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

export interface TranscriptionInsert {
  id: string; // UUID generated by the frontend for tracking the same turn
  meeting_id: string;
  speaker_id: string; 
  transcribe_text_segment: string;
  full_transcription: string;
  users_all: string[];
}

export class SupabaseService {
  /**
   * Upserts a transcription segment. If the ID exists, it updates the same row.
   */
  static async upsertTranscription(data: TranscriptionInsert): Promise<{ success: boolean; error?: string }> {
    try {
      const payload = {
        id: data.id,
        meeting_id: data.meeting_id,
        speaker_id: data.speaker_id,
        transcribe_text_segment: data.transcribe_text_segment,
        full_transcription: data.full_transcription,
        users_all: data.users_all || ['System']
      };

      const { error } = await supabase
        .from('transcriptions')
        .upsert([payload], { onConflict: 'id' });

      if (error) {
        return { success: false, error: error.message };
      }

      return { success: true };
    } catch (err: any) {
      console.error('Supabase Exception:', err);
      // More descriptive error for common fetch failures
      if (err instanceof TypeError && err.message === 'Failed to fetch') {
        return { success: false, error: "Network Error: Failed to reach Supabase. Check internet or rate limits." };
      }
      return { success: false, error: err.message || "Unknown Supabase error" };
    }
  }

  static async testConnection(): Promise<{ success: boolean; message: string }> {
    try {
      const { data, error } = await supabase
        .from('transcriptions')
        .select('id')
        .limit(1);
      
      if (error) throw error;
      return { success: true, message: "DB Connectivity Verified" };
    } catch (err: any) {
      return { success: false, message: err.message || "Schema mismatch or network error." };
    }
  }
}
