
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = 'https://xscdwdnjujpkczfhqrgu.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhzY2R3ZG5qdWpwa2N6Zmhxcmd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEzMzEwNjgsImV4cCI6MjA3NjkwNzA2OH0.xuVAkWA5y1oDW_jC52I8JJXF-ovU-5LIBsY9yXzy6cA';

export const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

export interface TranscriptionInsert {
  id: string; // UUID generated by the frontend for tracking the same turn
  meeting_id: string;
  speaker_id: string; 
  transcribe_text_segment: string;
  full_transcription: string;
  users_all: string[];
}

interface CacheEntry {
  fullText: string;
  segment: string;
  timestamp: number;
}

export class SupabaseService {
  private static lastUpdateCache = new Map<string, CacheEntry>();

  /**
   * Upserts a transcription segment. 
   * Optimized to only hit the API if changes are significant or enough time has passed.
   */
  static async upsertTranscription(data: TranscriptionInsert): Promise<{ success: boolean; error?: string }> {
    const now = Date.now();
    const cached = this.lastUpdateCache.get(data.id);

    // Significance logic to reduce load:
    // 1. If text is exactly identical to last sent, skip.
    // 2. If it's the first sync for this session ID, we MUST send it.
    // 3. If charsAdded > 40, it's a "significant" enough update.
    // 4. If > 10s passed, sync to ensure eventual consistency.
    
    if (cached) {
      const isIdentical = cached.fullText === data.full_transcription && cached.segment === data.transcribe_text_segment;
      if (isIdentical) return { success: true };

      const timeSinceLastUpdate = now - cached.timestamp;
      const charsAdded = Math.abs(data.full_transcription.length - cached.fullText.length);

      // Throttle minor updates unless 10 seconds have passed
      if (charsAdded < 40 && timeSinceLastUpdate < 10000) {
        return { success: true };
      }
    }

    try {
      const payload = {
        id: data.id,
        meeting_id: data.meeting_id,
        speaker_id: data.speaker_id,
        transcribe_text_segment: data.transcribe_text_segment,
        full_transcription: data.full_transcription,
        users_all: data.users_all || ['System']
      };

      const { error } = await supabase
        .from('transcriptions')
        .upsert([payload], { onConflict: 'id' });

      if (error) {
        return { success: false, error: error.message };
      }

      // Update cache on success
      this.lastUpdateCache.set(data.id, {
        fullText: data.full_transcription,
        segment: data.transcribe_text_segment,
        timestamp: now
      });

      return { success: true };
    } catch (err: any) {
      console.error('Supabase Exception:', err);
      if (err instanceof TypeError && err.message === 'Failed to fetch') {
        return { success: false, error: "Network Error: Failed to reach Supabase." };
      }
      return { success: false, error: err.message || "Unknown Supabase error" };
    }
  }

  static async testConnection(): Promise<{ success: boolean; message: string }> {
    try {
      const { data, error } = await supabase
        .from('transcriptions')
        .select('id')
        .limit(1);
      
      if (error) throw error;
      return { success: true, message: "DB Connectivity Verified" };
    } catch (err: any) {
      return { success: false, message: err.message || "Schema mismatch or network error." };
    }
  }

  /**
   * Resets the cache for a specific session.
   */
  static clearCache(id: string) {
    this.lastUpdateCache.delete(id);
  }
}
